-- 코드를 입력하세요
SELECT USER_ID, NICKNAME,
    CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, IFNULL(CONCAT(' ', U.STREET_ADDRESS2), '')) AS 전체주소, 
    CONCAT(LEFT(U.TLNO, 3), '-', SUBSTR(U.TLNO, 4, 4), '-', RIGHT(U.TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER U
WHERE 3 <= (
    SELECT COUNT(*)
    FROM USED_GOODS_BOARD
    WHERE U.USER_ID = WRITER_ID
)
ORDER BY U.USER_ID DESC;