-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT FH.FLAVOR, 
           FH.TOTAL_ORDER + IFNULL(SUM(J.TOTAL_ORDER), 0) AS TOTAL
    FROM FIRST_HALF FH
    LEFT JOIN JULY J ON FH.FLAVOR = J.FLAVOR
    GROUP BY FH.FLAVOR, FH.TOTAL_ORDER
) AS TOTAL_ORDERS
ORDER BY TOTAL DESC
LIMIT 3;
